dbt_itx:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 172.25.0.7
      port: 1433
      database: Northwind
      schema: psa
      user: sa
      password: Pass@word
      encrypt: false
      
      
